# app/routes/generate.py

from fastapi import APIRouter, HTTPException
from app.services.llm_study import generate_study_plan
from app.utils.logger import logger
import os
import json

router = APIRouter()

DATA_DIR = "/opt/render/project/src/data"


@router.post("/generate/")
async def generate(file_id: str, days: int, language: str):
    """
    Generate a structured learning plan based on previously analyzed document.
    Returns:
      - analysis block (loaded from <file_id>_analysis.json)
      - plan.days (generated by LLM)
    """

    logger.info(f"[GENERATE] Start → file_id='{file_id}' days={days} language='{language}'")

    # -----------------------------------------------------
    # 1. Load saved analysis block
    # -----------------------------------------------------
    analysis_path = os.path.join(DATA_DIR, f"{file_id}_analysis.json")

    if not os.path.exists(analysis_path):
        logger.error(f"[GENERATE] Analysis file NOT FOUND → {analysis_path}")
        raise HTTPException(status_code=500, detail="Analysis data not found")

    try:
        with open(analysis_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read analysis data: {e}")

    summary = data.get("summary", "")
    main_topics = data.get("main_topics", [])
    document_type = data.get("document_type", "document")
    level = data.get("level", "general")
    recommended_days = data.get("recommended_days", None)

    # -----------------------------------------------------
    # 2. Call LLM to generate plan
    # -----------------------------------------------------
    try:
        logger.info(f"[LLM_STUDY] Generating full plan for {days} days...")
        plan = await generate_study_plan(file_id, days, language)
        logger.info(f"[LLM_STUDY] Plan generated: {days} days")
    except Exception as e:
        logger.exception("[GENERATE] LLM generation failed")
        raise HTTPException(status_code=500, detail=f"Plan generation failed: {e}")

    # -----------------------------------------------------
    # 3. Build final response EXACTLY as frontend expects
    # -----------------------------------------------------
    response = {
        "status": "ok",
        "file_id": file_id,
        "days": days,
        "analysis": {
            "summary": summary,
            "main_topics": main_topics,
            "document_type": document_type,
            "level": level,
            "recommended_days": recommended_days,
        },
        "plan": {
            "days": plan  # plan must be an array of day objects
        }
    }

    logger.info("[GENERATE] Completed successfully")

    return response
